Fetch bijapur weather from openweather api and store in a file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,3 +15,40 @@ jobs:
       run: |
         ls
         git status
+    - name: Save current weather condition
+      env:
+        API_KEY: ${{ secrets.API_KEY }}
+      run: |
+        FILE=./data/`date +"%Y%m%d"`.json
+        if [ -f "$FILE" ]; then
+            echo "$FILE exists. Done for today."
+        else
+            echo "Begin to get today's weather condition."
+            url="https://api.openweathermap.org/data/2.5/weather?id=1275701&units=metric&appid="$API_KEY
+            response=$(curl -f "$url")
+            status=$?
+            if [ $status -eq 0 ]; then
+                echo $response > $FILE
+                echo "$FILE saved."
+                echo `date +"%Y%m%d"` >> ./data.txt
+            else
+                echo "curl exit code: ($status) $response"
+                exit $status
+            fi
+        fi
+    - name: git check in
+      env:
+        GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }} 
+        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
+      run: |
+        git config user.email "$GIT_OWNER_EMAIL"
+        git config user.name "amitmbee"
+        if [[ `git status --porcelain` ]]; then
+          git add .
+          git commit -a -m "add weather data"
+          git remote rm origin
+          git remote add origin https://amitmbee:$PUSH_TOKEN@github.com/amitmbee/vijayapura-historical-weather.git
+          git push origin HEAD:master
+        else
+          echo 'unable to detech changes'
+        fi
